name: "Install RtMidi"
description: "Install RtMidi library and headers"
runs:
  using: "composite"
  steps:
    - id: deps
      name: Dependencies
      shell: bash
      run: sudo apt-get -qq install libasound2-dev
    - id: download
      name: download
      shell: bash
      run: wget http://www.music.mcgill.ca/~gary/rtmidi/release/rtmidi-4.0.0.tar.gz -O /tmp/rtmidi-4.0.0.tar.gz
    - id: extract
      name: Extract
      shell: bash
      run: tar -xzf /tmp/rtmidi-4.0.0.tar.gz -C /tmp
    - id: install
      name: Install
      shell: bash
      run: cd /tmp/rtmidi-4.0.0 && ./configure && make && sudo make install
    - id: path
      name: path
      shell: bash
      run: echo "LD_LIBRARY_PATH=/usr/local/lib" >> $GITHUB_ENV
